[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/api/cars"
  to = "https://cars-by-api-ninjas.p.rapidapi.com/v1/cars?model=corolla"
  status = 200
  force = true
